import fs from "node:fs";
import path from "node:path";

// Next.js's server-file tracing can only discover files reachable through
// statically analyzable imports/requires - it can't know which files a
// runtime directory walk (getCookFiles) will touch, and outputFileTracingIncludes
// (the documented way to tell it anyway) is silently ignored by Turbopack's
// tracer as of Next.js 16.3.0. So the recipes' content is bundled as plain
// imported data instead: this generates a manifest of every .cook file's
// contents, which any bundler is guaranteed to include because it's a normal
// static import, not something tracing needs to discover.
const recipesDir = path.join(process.cwd(), "src/recipes");
const outputPath = path.join(
	process.cwd(),
	"src/utils/server/recipeManifest.generated.ts",
);

function walk(dir: string, base: string): Array<[string, string]> {
	const entries: Array<[string, string]> = [];

	for (const name of fs.readdirSync(dir)) {
		const fullPath = path.join(dir, name);
		const relativePath = base ? `${base}/${name}` : name;

		if (fs.statSync(fullPath).isDirectory()) {
			entries.push(...walk(fullPath, relativePath));
		} else if (name.endsWith(".cook")) {
			entries.push([relativePath, fs.readFileSync(fullPath, "utf-8")]);
		}
	}

	return entries;
}

const recipes = walk(recipesDir, "");

const contents = `// Generated by scripts/generateRecipeManifest.ts — do not edit by hand.
export const recipeManifest: Record<string, string> = ${JSON.stringify(
	Object.fromEntries(recipes),
	null,
	"\t",
)};
`;

fs.writeFileSync(outputPath, contents);
console.log(
	`generateRecipeManifest: wrote ${recipes.length} recipes to ${outputPath}`,
);
