import fs from "node:fs";
import path from "node:path";
import { parseRecipe } from "./parseRecipe";

// Next.js's server-file tracing can only discover files reachable through
// statically analyzable imports/requires - it can't know which files a
// runtime directory walk (getCookFiles) will touch, and outputFileTracingIncludes
// (the documented way to tell it anyway) is silently ignored by Turbopack's
// tracer as of Next.js 16.3.0. So each recipe's parsed data is bundled as
// plain imported data instead: this generates one file per recipe (mirroring
// src/recipes/<category>/<name>.cook), which any bundler is guaranteed to
// include because it's a normal static import, not something tracing needs
// to discover. Parsing (@cooklang/cooklang, gray-matter) happens here at
// build time rather than at request time, so neither dependency needs to
// ship in the runtime bundle.
//
// Splitting output per recipe - instead of one large object literal - lets
// the dynamic `/[slug]` route lazy-load just the one recipe it needs via
// `import()`, rather than every recipe's ingredients/steps being parsed and
// held in memory for every request. Pages that only need a title and a link
// (the homepage, search) read `recipeIndex.generated.ts` instead, which
// carries none of that per-recipe weight.
const recipesDir = path.join(process.cwd(), "src/recipes");
const outDir = path.join(process.cwd(), "src/utils/server");
const generatedDir = path.join(outDir, "generated");

function walk(dir: string, base: string): Array<[string, string]> {
	const entries: Array<[string, string]> = [];

	for (const name of fs.readdirSync(dir)) {
		const fullPath = path.join(dir, name);
		const relativePath = base ? `${base}/${name}` : name;

		if (fs.statSync(fullPath).isDirectory()) {
			entries.push(...walk(fullPath, relativePath));
		} else if (name.endsWith(".cook")) {
			entries.push([relativePath, fs.readFileSync(fullPath, "utf-8")]);
		}
	}

	return entries;
}

const cookFiles = walk(recipesDir, "");

fs.rmSync(generatedDir, { recursive: true, force: true });
fs.mkdirSync(generatedDir, { recursive: true });

const loaderEntries: string[] = [];
const summaryEntries: string[] = [];

for (const [relativePath, cookFileContent] of cookFiles) {
	const recipeData = parseRecipe(relativePath, cookFileContent);
	const [category, filename] = relativePath.split("/");
	const name = filename.replace(/\.cook$/, "");
	const slug = recipeData.slug ?? name;

	const categoryDir = path.join(generatedDir, category);
	fs.mkdirSync(categoryDir, { recursive: true });
	fs.writeFileSync(
		path.join(categoryDir, `${name}.generated.ts`),
		`// Generated by scripts/generateRecipeData.ts — do not edit by hand.
import type { RecipeData } from "../../getRecipeData/types";

export const recipeData: RecipeData = ${JSON.stringify(recipeData, null, "\t")};
`,
	);

	loaderEntries.push(
		`\t${JSON.stringify(relativePath)}: () => import(${JSON.stringify(`./generated/${category}/${name}.generated`)}),`,
	);
	summaryEntries.push(
		`\t${JSON.stringify({
			path: relativePath,
			slug,
			category,
			title: recipeData.metadata.title,
		})},`,
	);
}

fs.writeFileSync(
	path.join(outDir, "recipeDataLoaders.generated.ts"),
	`// Generated by scripts/generateRecipeData.ts — do not edit by hand.
import type { RecipeData } from "./getRecipeData/types";

export const recipeDataLoaders: Record<
	string,
	() => Promise<{ recipeData: RecipeData }>
> = {
${loaderEntries.join("\n")}
};
`,
);

fs.writeFileSync(
	path.join(outDir, "recipeIndex.generated.ts"),
	`// Generated by scripts/generateRecipeData.ts — do not edit by hand.
import type { RecipeSummary } from "./getRecipeData/types";

export const recipeIndex: RecipeSummary[] = [
${summaryEntries.join("\n")}
];
`,
);

console.log(
	`generateRecipeData: wrote ${cookFiles.length} recipes to ${generatedDir}`,
);
